receivers:
  otlp:
    protocols:
      grpc:
      http:        
  hostmetrics:
    scrapers:
      cpu:
      disk:
      filesystem:
      load:
      memory:
      network:
      process:
      processes:
      paging:

processors:
  batch:

exporters:
  logging:
    loglevel: info
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true      
  prometheus:
    endpoint: otel-collector:8889

extensions:
  health_check:
  pprof:  

service:
  telemetry:
    logs:
      level: DEBUG
    metrics:
      level: detailed
  extensions: [health_check, pprof]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp,logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheus]