receivers:
  otlp:
    protocols:
      grpc:
      http:
  hostmetrics:
    scrapers:
      cpu:
      # disk:
      # filesystem:
      # load:
      # memory:
      # network:
      # process:
      # processes:
      # paging:

processors:
  batch:

exporters:
  logging:
  otlp:
    endpoint: "tempo:4317"
  prometheus:
    namespace: "voice"
    endpoint: otel-collector:8889
  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write
    tls:
      insecure: true

extensions:
  health_check:
  pprof:

service:
  telemetry:
    logs:
      level: DEBUG
    metrics:
      level: detailed
  extensions: [health_check, pprof]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp,logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheusremotewrite]