apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    url: http://tempo:3200    
    basicAuth: false

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    basicAuth: false
  
  - name: k6influxdb
    type: influxdb
    access: proxy
    database: k6
    url: http://influxdb:8086
    isDefault: true